# Generated by Django 3.0.5 on 2022-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20220604_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='rawmaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('manufactuaring_date', models.DateField(max_length=100)),
                ('expiry_date', models.DateField(max_length=100)),
            ],
        ),
    ]
